image:
  file: .gitpod.dockerfile

tasks:
  - init: sdk use java 14.0.2.j9-adpt && exit
    command: cd mememedb

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
    onOpen: ignore

